// scripts/generate-components.ts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { globSync } from 'tinyglobby';

import pkg from '../package.json' with { type: 'json' };

const resolverDir = import.meta.dirname;
const packageRoot = path.resolve(resolverDir, '..');
const __filename = fileURLToPath(import.meta.url);

type ComponentExport = {
  exportName: string;
  sourcePath: string;
  componentNames: string[];
};

function toPosixPath(value: string) {
  return value.replaceAll(path.sep, '/');
}

function withDotSlash(value: string) {
  const posixPath = toPosixPath(value);
  return posixPath.startsWith('.') ? posixPath : `./${posixPath}`;
}

async function scanComponentExports() {
  const files = globSync('./src/components/**/index.ts', {
    cwd: packageRoot,
    absolute: true,
  });

  const result: ComponentExport[] = [];

  for (const indexFile of files) {
    const mod = (await import(pathToFileURL(indexFile).href)) as Record<string, unknown>;

    const exportName = path.basename(path.dirname(indexFile));

    const sourcePath = withDotSlash(path.relative(packageRoot, indexFile));

    const componentNames = Object.entries(mod)
      .filter(([, value]) => typeof value === 'string' && value.endsWith('.vue'))
      .map(([name]) => name);

    if (componentNames.length === 0) continue;

    result.push({
      exportName,
      sourcePath,
      componentNames,
    });
  }

  return result;
}

function updatePackageExports(items: ComponentExport[]) {
  const packageJsonPath = path.resolve(packageRoot, './package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

  packageJson.exports ??= {};

  for (const item of items) {
    packageJson.exports[`./${item.exportName}`] = item.sourcePath;
  }

  fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);
}

function generateComponentResolverJson(items: ComponentExport[]) {
  const jsonPath = path.resolve(packageRoot, 'resolver', 'components.json');

  const resolverMap = Object.fromEntries(
    items.flatMap(item =>
      item.componentNames.map(componentName => [componentName, `${pkg.name}/${item.exportName}`]),
    ),
  );

  fs.writeFileSync(jsonPath, `${JSON.stringify(resolverMap, null, 2)}\n`);
}

function generateType(items: ComponentExport[]) {
  const content = items
    .map(item =>
      item.componentNames.map(
        componentName =>
          `    ${componentName}: typeof import('@gr/ui/${item.exportName}')['${componentName}']`,
      ),
    )
    .flat()
    .join('\n');

  const code = `/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
${content}
  }
}
`;

  fs.writeFileSync(path.join(packageRoot, './types.d.ts'), code);
}

async function generate() {
  const items = await scanComponentExports();

  updatePackageExports(items);
  generateComponentResolverJson(items);
  generateType(items);

  console.log(`Generated ${items.length} component entries.`);
}

generate();
