/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../src/layouts/AppLayout.vue')['default']
    AppNav: typeof import('./../src/layouts/AppNav.vue')['default']
    AppSidebar: typeof import('./../src/layouts/AppSidebar.vue')['default']
    AppSidebarMenu: typeof import('./../src/layouts/AppSidebarMenu.vue')['default']
    BilibiliIcon: typeof import('@gr/ui/icons')['BilibiliIcon']
    Breadcrumb: typeof import('@gr/ui/breadcrumb')['Breadcrumb']
    BreadcrumbItem: typeof import('@gr/ui/breadcrumb')['BreadcrumbItem']
    BreadcrumbLink: typeof import('@gr/ui/breadcrumb')['BreadcrumbLink']
    BreadcrumbList: typeof import('@gr/ui/breadcrumb')['BreadcrumbList']
    BreadcrumbPage: typeof import('@gr/ui/breadcrumb')['BreadcrumbPage']
    BreadcrumbSeparator: typeof import('@gr/ui/breadcrumb')['BreadcrumbSeparator']
    Button: typeof import('@gr/ui/button')['Button']
    Card: typeof import('@gr/ui/card')['Card']
    CardContent: typeof import('@gr/ui/card')['CardContent']
    CardDescription: typeof import('@gr/ui/card')['CardDescription']
    CardHeader: typeof import('@gr/ui/card')['CardHeader']
    CardTitle: typeof import('@gr/ui/card')['CardTitle']
    Collapsible: typeof import('@gr/ui/collapsible')['Collapsible']
    CollapsibleContent: typeof import('@gr/ui/collapsible')['CollapsibleContent']
    CollapsibleTrigger: typeof import('@gr/ui/collapsible')['CollapsibleTrigger']
    DropdownMenu: typeof import('@gr/ui/dropdown-menu')['DropdownMenu']
    DropdownMenuContent: typeof import('@gr/ui/dropdown-menu')['DropdownMenuContent']
    DropdownMenuItem: typeof import('@gr/ui/dropdown-menu')['DropdownMenuItem']
    DropdownMenuTrigger: typeof import('@gr/ui/dropdown-menu')['DropdownMenuTrigger']
    Field: typeof import('@gr/ui/field')['Field']
    FieldDescription: typeof import('@gr/ui/field')['FieldDescription']
    FieldGroup: typeof import('@gr/ui/field')['FieldGroup']
    FieldLabel: typeof import('@gr/ui/field')['FieldLabel']
    FieldSeparator: typeof import('@gr/ui/field')['FieldSeparator']
    FluidCursor: typeof import('@gr/ui/fluid-cursor')['FluidCursor']
    Input: typeof import('@gr/ui/input')['Input']
    LoginForm: typeof import('./../src/components/LoginForm.vue')['default']
    NavMain: typeof import('./../src/layouts/NavMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('@gr/ui/separator')['Separator']
    Sidebar: typeof import('@gr/ui/sidebar')['Sidebar']
    SidebarContent: typeof import('@gr/ui/sidebar')['SidebarContent']
    SidebarFooter: typeof import('@gr/ui/sidebar')['SidebarFooter']
    SidebarGroup: typeof import('@gr/ui/sidebar')['SidebarGroup']
    SidebarGroupLabel: typeof import('@gr/ui/sidebar')['SidebarGroupLabel']
    SidebarHeader: typeof import('@gr/ui/sidebar')['SidebarHeader']
    SidebarInput: typeof import('@gr/ui/sidebar')['SidebarInput']
    SidebarInset: typeof import('@gr/ui/sidebar')['SidebarInset']
    SidebarMenu: typeof import('@gr/ui/sidebar')['SidebarMenu']
    SidebarMenuButton: typeof import('@gr/ui/sidebar')['SidebarMenuButton']
    SidebarMenuItem: typeof import('@gr/ui/sidebar')['SidebarMenuItem']
    SidebarMenuSub: typeof import('@gr/ui/sidebar')['SidebarMenuSub']
    SidebarMenuSubButton: typeof import('@gr/ui/sidebar')['SidebarMenuSubButton']
    SidebarMenuSubItem: typeof import('@gr/ui/sidebar')['SidebarMenuSubItem']
    SidebarOptInForm: typeof import('./../src/layouts/SidebarOptInForm.vue')['default']
    SidebarProvider: typeof import('@gr/ui/sidebar')['SidebarProvider']
    SidebarRail: typeof import('@gr/ui/sidebar')['SidebarRail']
    SidebarTrigger: typeof import('@gr/ui/sidebar')['SidebarTrigger']
    ThemeToggle: typeof import('@gr/ui/theme-toggle')['ThemeToggle']
    Toaster: typeof import('@gr/ui/sonner')['Toaster']
    ViyuniIcon: typeof import('./../src/components/ViyuniIcon.vue')['default']
    ViyuniLogo: typeof import('./../src/components/ViyuniLogo.vue')['default']
  }
}
